// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twizqbdwqglbmluycutz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3aXpxYmR3cWdsYm1sdXljdXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjk5NjgsImV4cCI6MjA3MzcwNTk2OH0.O0ybJW5smRc0ORy4AqUTl5W5aXGJEGmZfUGVbUJ_5xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});